#!/usr/bin/env python3
"""
Remove silence segments from a video and optionally add intro/outro.

Usage:
    python remove_silence.py <input_video> <segments_json> -o output.mp4
    python remove_silence.py <input_video> <segments_json> -o output.mp4 --intro inputs/intro.mp4 --outro inputs/outro.mp4

The segments JSON should have been generated by detect_silence.py.
Segments with "action": "remove" will be cut out; "keep" segments are preserved.
"""

import subprocess
import json
import re
import sys
import os
import time
import argparse
from pathlib import Path
from log_utils import setup_logger


def detect_hw_encoder():
    """Detect the best available hardware encoder. Returns encoder name or None."""
    candidates = [
        ("h264_nvenc", ["ffmpeg", "-f", "lavfi", "-i", "nullsrc=s=256x256:d=0.1",
                        "-c:v", "h264_nvenc", "-preset", "p4", "-f", "null", "-"]),
        ("h264_qsv",  ["ffmpeg", "-f", "lavfi", "-i", "nullsrc=s=256x256:d=0.1",
                        "-c:v", "h264_qsv", "-preset", "faster", "-f", "null", "-"]),
    ]
    for name, cmd in candidates:
        try:
            proc = subprocess.run(cmd, capture_output=True, timeout=10)
            if proc.returncode == 0:
                return name
        except Exception:
            continue
    return None


def video_encoder_args(crf, hw_encoder):
    """Return encoder flags for the detected encoder (or CPU fallback)."""
    if hw_encoder == "h264_nvenc":
        return ["-c:v", "h264_nvenc", "-preset", "p4", "-cq", str(crf)]
    if hw_encoder == "h264_qsv":
        return ["-c:v", "h264_qsv", "-preset", "faster", "-global_quality", str(crf)]
    return ["-c:v", "libx264", "-preset", "fast", "-crf", str(crf)]


def get_stream_info(filepath, log):
    """Get video/audio metadata via ffprobe."""
    log.debug(f"Probing: {filepath}")
    cmd = [
        "ffprobe", "-v", "quiet",
        "-print_format", "json",
        "-show_streams", "-show_format",
        filepath
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        log.error(f"Error probing {filepath}: {result.stderr}")
        sys.exit(1)
    data = json.loads(result.stdout)

    info = {"file": filepath}
    for s in data.get("streams", []):
        if s["codec_type"] == "video":
            info["video_codec"] = s["codec_name"]
            info["width"] = int(s["width"])
            info["height"] = int(s["height"])
            info["pix_fmt"] = s.get("pix_fmt", "yuv420p")
            num, den = s["r_frame_rate"].split("/")
            info["fps"] = round(int(num) / int(den), 3)
        elif s["codec_type"] == "audio":
            info["audio_codec"] = s["codec_name"]
            info["sample_rate"] = int(s.get("sample_rate", 48000))
            info["channels"] = int(s.get("channels", 2))

    info["duration"] = float(data.get("format", {}).get("duration", 0))
    log.debug(f"  -> {info.get('width','?')}x{info.get('height','?')} @ {info.get('fps','?')}fps, "
              f"duration={info['duration']:.1f}s, video={info.get('video_codec','?')}, audio={info.get('audio_codec','?')}")
    return info


def metadata_matches(main_info, other_info):
    """Check if video metadata is compatible for stream-copy concat."""
    keys = ["width", "height", "fps", "pix_fmt", "sample_rate", "channels"]
    for k in keys:
        if main_info.get(k) != other_info.get(k):
            return False
    return True


def reencode_to_match(source_path, main_info, output_path, log, hw_encoder=None):
    """Re-encode a video to match the main video's format."""
    w = main_info["width"]
    h = main_info["height"]
    fps = main_info["fps"]
    pix_fmt = main_info["pix_fmt"]
    sample_rate = main_info["sample_rate"]
    channels = main_info["channels"]

    cmd = [
        "ffmpeg", "-y",
        "-i", source_path,
        "-vf", f"scale={w}:{h}:force_original_aspect_ratio=decrease,"
               f"pad={w}:{h}:(ow-iw)/2:(oh-ih)/2,setsar=1",
        "-r", str(fps),
        "-pix_fmt", pix_fmt,
        *video_encoder_args(18, hw_encoder),
        "-ar", str(sample_rate),
        "-ac", str(channels),
        "-c:a", "aac", "-b:a", "128k",
        str(output_path),
    ]
    log.info(f"  Re-encoding {source_path} -> {output_path} ({w}x{h} @ {fps}fps)")
    log.debug(f"  CMD: {' '.join(cmd)}")
    t0 = time.time()
    proc = subprocess.run(cmd, capture_output=True, text=True)
    elapsed = time.time() - t0
    if proc.returncode != 0:
        log.error(f"  Re-encode failed ({elapsed:.1f}s): {proc.stderr[-500:]}")
        sys.exit(1)
    log.info(f"  Re-encode done in {elapsed:.1f}s")


def fmt_time(s):
    """Format seconds as HH:MM:SS.mmm"""
    h = int(s // 3600)
    m = int((s % 3600) // 60)
    sec = s % 60
    return f"{h:02d}:{m:02d}:{sec:06.3f}"


def fmt_duration_short(s):
    """Format seconds as a human-readable short string."""
    if s < 60:
        return f"{s:.1f}s"
    elif s < 3600:
        return f"{int(s//60)}m {int(s%60)}s"
    else:
        return f"{int(s//3600)}h {int((s%3600)//60)}m {int(s%60)}s"


def build_keep_intervals(segments, video_duration):
    """
    Given silence segments (action=remove), compute the intervals to KEEP.
    Returns list of (start, end) tuples.
    """
    remove = sorted(
        [(s["start"], s["end"]) for s in segments if s["action"] == "remove"],
        key=lambda x: x[0]
    )

    keep = []
    cursor = 0.0
    for rm_start, rm_end in remove:
        if rm_start > cursor:
            keep.append((cursor, rm_start))
        cursor = max(cursor, rm_end)
    if cursor < video_duration:
        keep.append((cursor, video_duration))

    return keep


def main():
    parser = argparse.ArgumentParser(
        description="Remove silence segments and optionally add intro/outro"
    )
    parser.add_argument("input", help="Input video file")
    parser.add_argument("segments", help="Silence segments JSON from detect_silence.py")
    parser.add_argument("-o", "--output", required=True, help="Output video path")
    parser.add_argument("--intro", default=None, help="Intro video to prepend")
    parser.add_argument("--outro", default=None, help="Outro video to append")
    parser.add_argument("--no-gpu", action="store_true", help="Disable GPU encoding (force CPU libx264)")
    args = parser.parse_args()

    log = setup_logger("remove_silence")
    log.info("=== remove_silence.py started ===")

    # ── GPU detection ──
    if args.no_gpu:
        hw_encoder = None
        log.info("GPU encoding disabled by --no-gpu flag")
    else:
        log.info("Checking for hardware encoders (NVENC, QSV)...")
        hw_encoder = detect_hw_encoder()
        if hw_encoder:
            log.info(f"Hardware encoding ENABLED ({hw_encoder})")
        else:
            log.info("No hardware encoder available — using CPU (libx264)")

    log.info(f"Input: {args.input}")
    log.info(f"Segments: {args.segments}")
    log.info(f"Output: {args.output}")
    log.info(f"Intro: {args.intro or 'none'}, Outro: {args.outro or 'none'}")
    run_start = time.time()

    input_path = os.path.abspath(args.input)
    output_path = os.path.abspath(args.output)
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    # ── Load segments ──
    log.info("Loading segments JSON...")
    with open(args.segments) as f:
        data = json.load(f)
    segments = data["segments"]

    remove_segments = [s for s in segments if s["action"] == "remove"]
    keep_segments = [s for s in segments if s["action"] == "keep"]
    log.info(f"Segments: {len(segments)} total, {len(remove_segments)} to remove, {len(keep_segments)} to keep")

    total_remove_time = sum(s["duration"] for s in remove_segments)
    log.info(f"Total silence to remove: {fmt_duration_short(total_remove_time)}")

    # ── Get main video info ──
    log.info(f"Probing main video: {input_path}")
    main_info = get_stream_info(input_path, log)
    video_duration = main_info["duration"]
    log.info(f"  Duration: {fmt_duration_short(video_duration)}")
    log.info(f"  Format:   {main_info['width']}x{main_info['height']} @ {main_info['fps']}fps")

    # ── Compute keep intervals ──
    keep_intervals = build_keep_intervals(segments, video_duration)
    total_keep_time = sum(end - start for start, end in keep_intervals)
    log.info(f"Keep intervals: {len(keep_intervals)} chunks, total {fmt_duration_short(total_keep_time)}")
    log.info(f"Expected output duration: ~{fmt_duration_short(total_keep_time)}")
    log.debug(f"First 5 keep intervals: {keep_intervals[:5]}")
    log.debug(f"Last 5 keep intervals: {keep_intervals[-5:]}")

    # ── Prepare intro/outro if needed ──
    temp_dir = Path(os.path.dirname(output_path)) / "_temp_build"
    temp_dir.mkdir(parents=True, exist_ok=True)
    log.debug(f"Temp dir: {temp_dir}")

    prepared_intro = None
    prepared_outro = None

    if args.intro:
        intro_path = os.path.abspath(args.intro)
        log.info(f"Checking intro: {intro_path}")
        intro_info = get_stream_info(intro_path, log)
        if not metadata_matches(main_info, intro_info):
            log.info("Intro metadata differs — re-encoding to match main video.")
            prepared_intro = str(temp_dir / "intro_matched.mp4")
            reencode_to_match(intro_path, main_info, prepared_intro, log, hw_encoder)
        else:
            log.info("Intro metadata matches main video.")
            prepared_intro = intro_path

    if args.outro:
        outro_path = os.path.abspath(args.outro)
        log.info(f"Checking outro: {outro_path}")
        outro_info = get_stream_info(outro_path, log)
        if not metadata_matches(main_info, outro_info):
            log.info("Outro metadata differs — re-encoding to match main video.")
            prepared_outro = str(temp_dir / "outro_matched.mp4")
            reencode_to_match(outro_path, main_info, prepared_outro, log, hw_encoder)
        else:
            log.info("Outro metadata matches main video.")
            prepared_outro = outro_path

    # ── Build the main cleaned video using select/aselect filters ──
    log.info("")
    log.info("=" * 60)
    log.info(f"Building cleaned video ({len(keep_intervals)} keep intervals)...")
    log.info("=" * 60)

    # Build select expression: between(t,start,end)+between(t,start,end)+...
    select_parts = [f"between(t\\,{s:.3f}\\,{e:.3f})" for s, e in keep_intervals]
    select_expr = "+".join(select_parts)
    log.debug(f"Select expression length: {len(select_expr)} chars")

    main_output = str(temp_dir / "main_cleaned.mp4") if (prepared_intro or prepared_outro) else str(output_path)
    log.debug(f"Main output target: {main_output}")

    cmd = [
        "ffmpeg", "-y",
        "-i", input_path,
        "-vf", f"select='{select_expr}',setpts=N/FRAME_RATE/TB",
        "-af", f"aselect='{select_expr}',asetpts=N/SR/TB",
        *video_encoder_args(18, hw_encoder),
        "-c:a", "aac", "-b:a", "128k",
        "-movflags", "+faststart",
        main_output,
    ]
    log.debug(f"CMD length: {len(' '.join(cmd))} chars")

    log.info(f"Running ffmpeg single-pass select filter...")
    log.info(f"Processing full {fmt_duration_short(video_duration)} input -> ~{fmt_duration_short(total_keep_time)} output")
    encode_start = time.time()

    proc = subprocess.Popen(
        cmd, stderr=subprocess.PIPE, stdout=subprocess.PIPE, text=True
    )

    # Parse ffmpeg progress from stderr
    last_report = 0
    for line in proc.stderr:
        log.debug(f"ffmpeg: {line.rstrip()}")
        # ffmpeg outputs progress like: frame=  123 fps=45 ... time=00:01:23.45 ...
        time_match = re.search(r"time=(\d+):(\d+):([\d.]+)", line)
        if time_match:
            h, m, s = int(time_match.group(1)), int(time_match.group(2)), float(time_match.group(3))
            current_out = h * 3600 + m * 60 + s
            elapsed = time.time() - encode_start
            if elapsed > 0 and current_out > 0 and elapsed - last_report >= 2:
                speed = current_out / elapsed
                remaining_out = total_keep_time - current_out
                eta = remaining_out / speed if speed > 0 else 0
                pct = min(current_out / total_keep_time * 100, 100)
                msg = (f"  {pct:5.1f}%  output: {fmt_time(current_out)}  "
                       f"speed: {speed:.1f}x  elapsed: {fmt_duration_short(elapsed)}  "
                       f"ETA: {fmt_duration_short(eta)}")
                log.info(msg)
                last_report = elapsed

    proc.wait()
    encode_time = time.time() - encode_start

    if proc.returncode != 0:
        log.error(f"ffmpeg encoding failed (exit code {proc.returncode})")
        sys.exit(1)

    log.info(f"Encoding done in {fmt_duration_short(encode_time)}")

    # ── Concatenate intro + main + outro if needed ──
    # Stream-copy concat: intro/outro must already match the main video's
    # format (use inputs/intro_matched.mp4 etc.). This is near-instant.
    concat_time = 0
    if prepared_intro or prepared_outro:
        log.info("Concatenating intro/main/outro (stream-copy)...")
        concat_start = time.time()

        concat_list = temp_dir / "concat.txt"
        with open(concat_list, "w") as f:
            if prepared_intro:
                safe = str(Path(prepared_intro).resolve()).replace("\\", "/")
                f.write(f"file '{safe}'\n")
                log.debug(f"  Concat entry: intro -> {safe}")
            safe = str(Path(main_output).resolve()).replace("\\", "/")
            f.write(f"file '{safe}'\n")
            log.debug(f"  Concat entry: main -> {safe}")
            if prepared_outro:
                safe = str(Path(prepared_outro).resolve()).replace("\\", "/")
                f.write(f"file '{safe}'\n")
                log.debug(f"  Concat entry: outro -> {safe}")

        cmd = [
            "ffmpeg", "-y",
            "-f", "concat", "-safe", "0",
            "-i", str(concat_list),
            "-c", "copy",
            "-movflags", "+faststart",
            str(output_path),
        ]
        log.debug(f"Concat CMD: {' '.join(cmd)}")
        proc = subprocess.run(cmd, capture_output=True, text=True)
        concat_time = time.time() - concat_start

        if proc.returncode != 0:
            log.error(f"Concat failed: {proc.stderr[-500:]}")
            sys.exit(1)
        log.info(f"Concat done in {fmt_duration_short(concat_time)}")

    # ── Cleanup temp files ──
    log.info("Cleaning up temp files...")
    for tmp_file in temp_dir.glob("*"):
        try:
            log.debug(f"  Deleting: {tmp_file}")
            tmp_file.unlink(missing_ok=True)
        except PermissionError:
            log.debug(f"  Skipped (locked): {tmp_file}")
    try:
        temp_dir.rmdir()
    except OSError:
        log.debug(f"  Could not remove temp dir (not empty): {temp_dir}")

    # ── Final report ──
    log.info("Probing output file...")
    output_info = get_stream_info(output_path, log)
    output_size_mb = os.path.getsize(output_path) / (1024 * 1024)
    total_elapsed = time.time() - run_start

    log.info("")
    log.info("=" * 60)
    log.info("  DONE")
    log.info("=" * 60)
    log.info(f"  Input duration:    {fmt_duration_short(video_duration)}")
    log.info(f"  Silence removed:   {fmt_duration_short(total_remove_time)} ({len(remove_segments)} segments)")
    log.info(f"  Output duration:   {fmt_duration_short(output_info['duration'])}")
    log.info(f"  Time saved:        {total_remove_time/video_duration*100:.1f}% of original")
    log.info(f"  Output file:       {output_path}")
    log.info(f"  Output size:       {output_size_mb:.1f} MB")
    log.info(f"  Encoding took:     {fmt_duration_short(encode_time)}")
    log.info(f"  Concat took:       {fmt_duration_short(concat_time)}")
    log.info(f"  Total wall time:   {fmt_duration_short(total_elapsed)}")
    log.info("=" * 60)
    log.info("=== remove_silence.py finished ===")


if __name__ == "__main__":
    main()
